### PR TITLE
Add a note about ZFS volume encryption

### PR DESCRIPTION
**Pull request by okasprowicz-reef**
I think this is viable to satisfy the security requirements for 1st phase of the evaluation period if someone already uses ZFS. Might be too niche to include in the handbook though...

### CODE REVIEW

**Comment by mjurbanski-reef** [comment]
Most likely too niche indeed - to keep the handbook size manageable, we prefer to keep options to some small subset of "safe defaults" - there are just too many options to cover all of them after all.

The folder level encryption for developers is, in fact, discouraged since you would also need to reconfigure docker etc, for it to work properly.
On the docker part - IIRC docker configuration by default will error out if try to create docker container volumes on ZFS, which would be another.

During 1st and 2nd phase of evaluation period, storage encryption is not needed at all https://github.com/reef-technologies/handbook?tab=readme-ov-file#storage-encryption-and-secure-work-environment
If this point is unclear, then I guess it should be rephrased.

**Comment by mjurbanski-reef** [comment]
@adal-chiriliuc-reef I think you have worked on opensource or internal projects basically the whole time, hence why.
IDK if you already had the note about secure working environment when you started to work on you tasks 4-7 - I tend to delete it whenever I know someone doesn't need it quite yet.
But for sure we should at the end of the Evaluation period ensure the Secure Working Environmnet is in place.

**Comment by okasprowicz-reef** [comment]
> All data pertaining **to the company** and its clients must be either stored in the cloud (specifically, Google Drive/Docs/Sheets within the company domain) or **on encrypted media (an encrypted volume or drive).**

@mjurbanski-reef this point got me confused - I understood that the Secure Work Environment is **not** required (so: at least user level isolation, etc), _however_ **any** company-related data should be encrypted (therefore: volume).

> On the docker part - IIRC docker configuration by default will error out if try to create docker container volumes on ZFS, which would be another.

Nit: it has been working for me out of the box (same with `podman`) - either NixOs took care of it or it had been fixed at the Docker level

**Comment by mjurbanski-reef** [comment]
I guess we need to rethink how to phrase that more clearly.

The slight problem is that we try to use same instruction for Reef Assistants and Developer at the same time, hence why it gets confusing... tbh I don't think Assistants read this stuff from top to bottom, so if I'm right and they use only fragments of it anyhow, then the instruction could be simplified and therefor more clear.

Will confirm internally.

Thanks for bringing it up.

**Comment by rooterkyberian** [comment]
We have decided that Reef assistants are not required to read this repo, so expect some simplifications to come to it.

**Comment by mjurbanski-reef** [comment]
Reef assistsants will no longer be required to follow handbook repo, so we will introduce some further simplificantion to the mentioned instructions.

**Pull request closed without merging**
